# Layer 1 Rules for SmsPolicyCheckerService
# See README.md Section 4.2 for detailed structure.
#
# - name: Unique rule identifier (String)
#   description: Human-readable description (String)
#   type: "keyword" or "regex" (String)
#   patterns: Array of strings (keywords or regex patterns)
#   mapped_policy_category: Internal policy category string (e.g., "SHAFT-Sex")
#   individual_confidence: Float (0.0-1.0) - confidence of violation on match
#   is_early_exit_rule: Boolean (true/false)
#   early_exit_threshold: Float (0.0-1.0) - if is_early_exit_rule is true

- name: "L1_SHAFT_SEX_EXPLICIT_KEYWORD"
  description: "Detects unambiguously explicit sexual terms."
  type: "keyword"
  patterns:
    - "hardcore sex"
    - "explicit video"
    # ... more highly specific and unambiguous terms
  mapped_policy_category: "SHAFT-Sex"
  individual_confidence: 1.0
  is_early_exit_rule: true
  early_exit_threshold: 1.0

- name: "L1_PUBLIC_URL_SHORTENER"
  description: "Detects the use of common, free public URL shorteners."
  type: "regex"
  patterns:
    - "(bit\\.ly|tinyurl\\.com|goo\\.gl|t\\.co|is\\.gd|ow\\.ly)\\/[a-zA-Z0-9]+"
    # Add more shortener domains as needed
  mapped_policy_category: "Prohibited-URL-Shortener"
  individual_confidence: 0.90
  is_early_exit_rule: true
  early_exit_threshold: 0.90

- name: "L1_EXCESSIVE_CAPITALIZATION"
  description: "Detects excessive use of uppercase letters."
  type: "regex"
  patterns:
    - "(?:[A-Z]\\s*){15,}" # 15 or more capital letters, possibly with spaces
  mapped_policy_category: "Content-Evasion-Spam"
  individual_confidence: 0.70
  is_early_exit_rule: false
  # early_exit_threshold: not needed if not an early exit rule
