# Thresholds for SmsPolicyCheckerService
# See README.md Section 8.

# General threshold above which a message is flagged as :fail in full_analysis mode,
# if no critical or Layer 1 early exit occurs.
# (README Section 6.1, 6.3.b)
FINAL_THRESHOLD_FLAG: 0.75

# Threshold for Layer 1 only fallback mode.
# (README Section 7)
FINAL_THRESHOLD_FLAG_FOR_L1_FALLBACK: 0.70 # Can be same or different from above

# Critical Failure definitions for Layer 2 analysis.
# If a policy_category_score from Layer 2 meets or exceeds its threshold,
# it's a critical failure.
# (README Section 6.3.a)
CRITICAL_FAILURE_THRESHOLDS:
  # "MisleadingSenderIdentity": 0.95
  # "FalseOrInaccurateContent": 0.95
  # "HatefulContent": 0.95
  # "ServiceInterferenceOrFilterEvasion": 0.95
  # "SHAFT_Sex_AdultContent": 0.98
  # "SHAFT_Alcohol_ProhibitedPromotion": 0.95
  # "SHAFT_Firearms_IllegalPromotion": 0.95
  # "SHAFT_Tobacco_ProhibitedPromotion": 0.95
  # "ProhibitedSubstances_CannabisCBDKratom": 0.95
  # "RegulatedPharmaceuticals_PrescriptionOffers": 0.95
  # "FraudulentOrMaliciousContent": 0.95
  # "HighRiskFinancialServices": 0.95
  # "ProhibitedAffiliateMarketing": 0.95
  # "RestrictedDebtCollection": 0.95
  # "GetRichQuickSchemes": 0.95
  # "GamblingPromotions": 0.95
  # "PhishingAndDeceptiveURLs": 0.95
  # "ProhibitedPublicURLShorteners": 0.95
  "AdvancedContentEvasionTactics": 0.95
